pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo "Build stage - nothing to compile for Python"
            }
        }

        stage('Test') {
            steps {
                sh '''  
                python3 - <<EOF
import sys                                                                    
sys.path.insert(0, 'bits-ls1-2025sl93071') 
import calculator

assert calculator.add(2,3) == 5
assert calculator.subtract(5,3) == 2
assert calculator.multiply(2,3) == 6
assert calculator.divide(6,3) == 2

print("All tests passed")
EOF
                '''
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploy stage (dummy for now)"
            }
        }
    }
}
